fun main(){
    print("Student Enrollment No :")
    val Enrollment_no = readLine()
    print(" Student Name :")
    val Name = readLine()
    print("Studenyt Branch :")
    val Branch = readLine()
    print("Student Class :")
    val Class = readLine()
    print("Student Batch :")
    val Batch = readLine()
    print("Student College Name :")
    val College_Name = readLine()
    print("Student University Name:")
    val University_Name = readLine()
    print("Student Age :")
    val Age = readLine()
    println("****************************************************************************")

    println("Student Data :")
    println("Enrollment No : $Enrollment_no")
    println("Name :$Name")
    println("AGE:$Age")
    println("Branch :$Branch")
    println("Class : $Class")
    println("Batch : $Batch")
    println("College Name :$College_Name")
    println("University Name : $University_Name")

}